---
title: "1.2 — Scarcity, Choice, & Cost — Class Content"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

- Section 1: *Monday, February 1, 2021*
- Section 2: *Tuesday, February 2, 2021*

# <i class="fas fa-info-circle fa-lg"></i> Overview

We are diving right into what is commonly called "Consumer Theory." This is often the most "alien" material to students in economics: indifference curves, preferences

constrained optimization models.

If you are following the textbook, it goes straight into (a review of principles, really) supply & demand. We will ultimately get to supply and demand, but by the time we do later this semester, you will have a *much* richer understanding and appreciation for them, having understood **how they represent the decisions by optimizing individuals as buyers and sellers.**

What we turn to now, for the next few classes, 

and our first application, how individuals choose. Our primary focus will be people as consumers - how do they choose to spend their money and how do those choices change? While we will focus extensively on consumers making purchasing choices, do not think this is the only use of this type of model! Today we will cover the *constraints* in the model.

As it is still only the first week of class: if you have not done so, please watch my welcome video, read the announcements in Blackboard, take my survey, and join our class slack channel.

The live class <i class="fas fa-video"></i> Zoom meeting link can be found on Blackboard (see `LIVE ZOOM MEETINGS` on the left navigation menu), starting at 2:00 PM.

If you are unable to join today's live session, or if you want to review, you can find the recording stored on Blackboard via Panopto (see `Class Recordings` on the left navigation menu).

Please note, the lesson numbers (e.g. 1.1) are *my* design, and do not match up with the textbook!

# <i class="fas fa-book-reader fa-lg"></i> Readings

- <i class="fas fa-book"></i> Ch. 4.3 in @textbook
- <i class="fas fa-external-link-square-alt"></i> Bastiat, 1848 [“What is Seen and Not Seen”](https://www.econlib.org/library/Bastiat/basEss.html?chapter_num=4#book-reader), (Section 1)
- [<i class="fas fa-file-pdf"></i> Math Review Guide](/files/math_review_guide.pdf) 

Now that we are picking up the intensity and working with some models (many will be new to you at first), I recommend looking at the textbook readings for each class.

We are going a bit out of order in two ways. First, Goolsbee et al. start with a review of Supply and Demand in chapters 2-3, and don't get to "Consumer Theory" (what we are starting now) until chapter 4. Second, they start with the "newer" and "weirder" stuff first — indifference curves and utility functions, and then teach budget constraints second. I will go in the *opposite* order to slowly acclimate you from familiar territory (linear equations) into newer tools and concepts (nonlinear functions, multivariate functions, optimization, etc). This is also a good time to review my [Math Review Guide](/files/math_review_guide.pdf) for next week.

# <i class="fas fa-chalkboard-teacher"></i> Slides

- [<i class="fas fa-chalkboard-teacher"></i> View Lecture Slides](/slides/1.1-slides.html)
- [<i class="fas fa-file-pdf"></i> Download as PDF](/slides/1.1-slides.pdf)

# <i class="fas fa-dumbbell"></i> Practice

NONE

# <i class="fas fa-laptop-code"></i> Assignments

## Preliminary Survey

Please take the [preliminary survey](/assignment/00-preliminary-survey) on your math background by 11:59 PM Sunday. This will help us all have a productive course together.
