baseurl: "https://microS21.classes.ryansafner.com/"
languageCode: "en-us"
title: "Microeconomic Analysis"
theme: "rvs-tufte-hugo"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
  - \.knit\.md
  - \.utf8\.md
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Assignments
      url: /assignments/
      weight: 3
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: Reference
      url: /reference/
      weight: 5
    - name: Slack
      url: "https://hoodcollegeeconomics.slack.com"
      weight: 7
# Disable taxonomies
taxonomies:
  tag: ""
  group: ""
  category: ""
params:
  author: Ryan Safner
  thumbnail: /images/micro_hex.png
  instructor: 
    name: Dr. Ryan Safner
    email: safner@hood.edu
    url: "https://www.ryansafner.com"
    twitter: ryansafner
    github: ryansafner
    office: 118 Rosenstock
  course:
    number: ECON 306
    semester: Spring 2021
    days: MW (Section 1)
      
      TuTh (Section 2)
    time: >-
      2:00 PM–3:15 PM (Both Sections)
    location: 'Meets on Zoom'
    twitter: ryansafner
    dates: >-
      February 1–May 21, 2021
    github: "ryansafner/microS21"
    slack: "http://hoodcollegeeconomics.slack.com"
    copyrightYear: "2020-2021"
    contactDetails: >-
      Office hours: TBD on Zoom
  university: 
    name: Hood College
    url: "https://www.hood.edu"
  school:
    name: George B. Delaplaine, Jr. School of Business
    url: "https://www.hood.edu/academics/departments/george-b-delaplaine-jr-school-business"
  description: "Microeconomic analysis"
  primaryColor: "#5E81AC"
  secondaryColor: "#D08770"
  credits: >- 
    [Credits](/credits)
  logo:
    url: /images/micro_hex.png
    alt: Microeconomics
  meta:
    twitterSite: "@ryansafner"
    twitterCreator: "@ryansafner"
    fbAuthor: "https://www.facebook.com/ryansafner"
