---
title: "Assignments"
slug: assignments
---

## Grade Calculator

- [<i class="fas fa-calculator"></i> `Grade Calculator`](https://ryansafner.shinyapps.io/306_grade_calculator/)

Use this tool to calculate your final course grade and predict what grades you would need on remaining assignments to obtain a desired course grade.

### Homeworks

There will be roughly a homework assignment every few lessons. These questions will help check your understanding and mastery of the material, and will be a combination of quantitative, graph, and short answer questions of examples. These will also be good indicators of what to expect on the exams. You may collaborate with other students to work on homeworks (and I encourage that!), but each person must turn in an individual assignment.

Homeworks are generally due by 11:59 PM EST Sunday by submission to Blackboard Assignments.

Please **type** your answers to the following questions in a document and **save as a PDF**^[In MS Word, or Pages, or most word processing software, File -> Save As -> PDF, or File -> Export -> PDF.] to **upload on Blackboard** under Assignments. You may handwrite answers if you will be able to scan/photograph & convert them **to a single PDF**, if they are easily readable, but this is *not preferred*. See my [guide to making a PDF](https://microS21.classes.ryansafner.com/resources/#how-to-make-a-pdf-for-submitting-assignments) - an essential skill in the modern world. If you are handwriting answers, you may print the `pdf` above and write on it, or just write on a piece of paper (we only need your answers).

For the few questions that ask you to draw a **graph**, *try* to do so *on your computer* (use MS Paint, the drawing tools in MS Word or MS Powerpoint, plot points in MS Excel, drawing/notetaking apps, etc.), and save it as an image to include on your homework document. Again, they need not be perfect or to scale, just show that you understand the broad idea. Being able to understand and sketch the graphs is still a very important and useful skill! If all else fails, I will be lenient in grading graph questions if you are unable to technologically include a graph. 

Your TA, under my supervision, will grade homeworks 70% for completion, and for the remaining 30%, and one question will be graded for accuracy - so it is best that you try every problem, even if you are unsure how to complete it accurately.

| Assignment         | Deadline (S1 MW/S2 TuTh) |
|--------------------|---------:|
| [Preliminary Survey](/assignment/00-preliminary-survey) | Sun Feb 7 |
| [Problem Set 1](/assignment/01-problem-set) | Wed Feb 17|
| [Problem Set 2](/assignment/02-problem-set) | Sun Feb 28 |
| [Problem Set 3](/assignment/03-problem-set) | Sun Mar 14/21 |
| [Problem Set 4](/assignment/04-problem-set) | Sun Mar 28/April 4 |
| [Problem Set 5](/assignment/05-problem-set) | Sun Apr 25 |
| [Problem Set 6](/assignment/06-problem-set) | TBD |

### Exams

There will be three exams (one at the end of each unit) including the final exam. Exams are a combination of True/False/Uncertain and Explain, Short Answer, Long Answer, and Problems similar to homeworks. These provide feedback both to you and to me that ensures everyone is progressing on schedule and apprehending the material. This is *critical*, as the rest of the course, and indeed, any future economics course you take, will build off of this foundation. I will announce the date of each exam several weeks in advance. 

| Assignment         | Deadline (S1 MW/S2 TuTh) |
|--------------------|---------:|
| [Exam 1](/assignment/01-exam) | Mar 1—Mar 7/Mar 3—Mar 10 |
| [Exam 2](/assignment/02-exam) | Apr 5-Apr 11|
| [Final Exam](/assignment/03-exam) | TBD |

### Opinion-Editorial

Economic fallacies have always been popular, and journalists, politicians, and talking heads consistently engage in faulty economic reasoning in print and on television. Your task, as a student of economics, is to find some issue discussed in the past year, and write a critique of media discussion of that issue. Alternatively, instead of critiquing the reasoning or statements of others, you may write an advocacy piece, where you propose some economic policy and argue to persuade readers to endorse it. You will be graded both on the soundness of your economic reasoning and the quality of your writing. I would be happy to co-author an Op-Ed with anyone who writes an exemplary Op-Ed. Students who successfully publish their work in a media outlet will earn *extra credit* on their Op-Ed grade. I will provide ample resources and examples to help you accomplish this, you can find more on the associated [assignment page](assignment/op-ed). 

| Assignment         | Deadline |
|--------------------|---------:|
| [Op-Ed](/assignment/op-ed) | May 9 |

<span class="newthought">No extra credit is available.</span>